import type { StationColumnConfig } from '@/services/snowobs/transform'

// Canonical region order for grouping the station index, matching the legacy
// nwac.us /weatherdata/ directory.
export const STATION_REGIONS = [
  'Olympics',
  'Mt Baker',
  'West',
  'Mountain Loop',
  'Stevens Pass',
  'Snoqualmie Pass',
  'Crystal Mt.',
  'Mt Rainier',
  'Chinook Pass',
  'White Pass',
  'Mt St Helens',
  'Washington Pass',
  'Lake Wenatchee to Mission Ridge',
  'Mt Hood',
] as const

export type StationRegion = (typeof STATION_REGIONS)[number]

export type WeatherStationGroup = {
  slug: string
  /** Old nwac.us /weatherdata/<slug>/now/ slug, kept for future redirects. */
  legacySlug: string
  displayName: string
  region: StationRegion
  /** Unique SnowObs station ids fetched for this group. */
  stids: string[]
  columns: StationColumnConfig[]
}

// Ported from the legacy nwac_weatherstation plugin's station_group_tables_config.
export const WEATHER_STATION_GROUPS: WeatherStationGroup[] = [
  {
    slug: 'hurricane-ridge',
    legacySlug: 'hurricaneridge',
    displayName: 'Hurricane Ridge',
    region: 'Olympics',
    stids: ['4'],
    columns: [
      ['4', 'air_temp'],
      ['4', 'relative_humidity'],
      ['4', 'wind_speed_min'],
      ['4', 'wind_speed'],
      ['4', 'wind_gust'],
      ['4', 'wind_direction'],
      ['4', 'precip_accum_one_hour'],
      ['4', 'snow_depth'],
      ['4', 'solar_radiation'],
    ],
  },
  {
    slug: 'mt-baker-ski-area',
    legacySlug: 'mtbakerskiarea',
    displayName: 'Mt. Baker Ski Area',
    region: 'Mt Baker',
    stids: ['6', '5'],
    columns: [
      ['6', 'air_temp'],
      ['5', 'air_temp'],
      ['6', 'relative_humidity'],
      ['5', 'relative_humidity'],
      ['6', 'wind_speed_min'],
      ['6', 'wind_speed'],
      ['6', 'wind_gust'],
      ['6', 'wind_direction'],
      ['5', 'precip_accum_one_hour'],
      ['5', 'snow_depth_24h'],
      ['5', 'snow_depth'],
      ['6', 'solar_radiation'],
    ],
  },
  {
    slug: 'newhalem',
    legacySlug: 'newhalem',
    displayName: 'Newhalem',
    region: 'West',
    stids: ['59'],
    columns: [
      ['59', 'air_temp'],
      ['59', 'relative_humidity'],
      ['59', 'wind_speed_min'],
      ['59', 'wind_speed'],
      ['59', 'wind_gust'],
      ['59', 'wind_direction'],
      ['59', 'snow_depth'],
    ],
  },
  {
    slug: 'white-chuck',
    legacySlug: 'whitechuck',
    displayName: 'White Chuck',
    region: 'Mountain Loop',
    stids: ['57'],
    columns: [
      ['57', 'air_temp'],
      ['57', 'relative_humidity'],
      ['57', 'wind_speed_min'],
      ['57', 'wind_speed'],
      ['57', 'wind_gust'],
      ['57', 'wind_direction'],
      ['57', 'snow_depth'],
      ['57', 'solar_radiation'],
    ],
  },
  {
    slug: 'berne',
    legacySlug: 'bernemaintenancestation',
    displayName: 'Berne',
    region: 'Stevens Pass',
    stids: ['12'],
    columns: [
      ['12', 'air_temp'],
      ['12', 'relative_humidity'],
      ['12', 'precip_accum_one_hour'],
      ['12', 'snow_depth_24h'],
      ['12', 'snow_depth'],
      ['12', 'pressure'],
    ],
  },
  {
    slug: 'stevens-pass-schmidt-haus',
    legacySlug: 'stevenshwy2',
    displayName: 'Stevens Pass - WSDOT Schmidt Haus',
    region: 'Stevens Pass',
    stids: ['13'],
    columns: [
      ['13', 'air_temp'],
      ['13', 'relative_humidity'],
      ['13', 'precip_accum_one_hour'],
      ['13', 'snow_depth_24h'],
      ['13', 'snow_depth'],
      ['13', 'pressure'],
    ],
  },
  {
    slug: 'stevens-pass-brooks',
    legacySlug: 'brookssnow',
    displayName: 'Stevens Pass Ski Area - Brooks Chair',
    region: 'Stevens Pass',
    stids: ['50'],
    columns: [
      ['50', 'air_temp'],
      ['50', 'relative_humidity'],
      ['50', 'precip_accum_one_hour'],
      ['50', 'snow_depth_24h'],
      ['50', 'snow_depth'],
    ],
  },
  {
    slug: 'stevens-pass-grace-lakes',
    legacySlug: 'gracelakes',
    displayName: 'Stevens Pass - Grace Lakes & Old Faithful',
    region: 'Stevens Pass',
    stids: ['14', '51'],
    columns: [
      ['14', 'air_temp'],
      ['14', 'relative_humidity'],
      ['51', 'wind_speed_min'],
      ['51', 'wind_speed'],
      ['51', 'wind_gust'],
      ['51', 'wind_direction'],
      ['14', 'snow_depth'],
      ['14', 'intermittent_snow'],
    ],
  },
  {
    slug: 'stevens-pass-ski-area',
    legacySlug: 'stevensskiarea',
    displayName: 'Stevens Pass Ski Area',
    region: 'Stevens Pass',
    stids: ['18', '17'],
    columns: [
      ['18', 'air_temp'],
      ['17', 'air_temp'],
      ['17', 'relative_humidity'],
      ['18', 'wind_speed_min'],
      ['18', 'wind_speed'],
      ['18', 'wind_gust'],
      ['18', 'wind_direction'],
    ],
  },
  {
    slug: 'alpental-ski-area',
    legacySlug: 'alpental',
    displayName: 'Alpental Ski Area',
    region: 'Snoqualmie Pass',
    stids: ['3', '2', '1'],
    columns: [
      ['3', 'air_temp'],
      ['2', 'air_temp'],
      ['1', 'air_temp'],
      ['3', 'relative_humidity'],
      ['1', 'relative_humidity'],
      ['3', 'wind_speed'],
      ['3', 'wind_gust'],
      ['3', 'wind_direction'],
      ['1', 'precip_accum_one_hour'],
      ['1', 'snow_depth_24h'],
      ['1', 'snow_depth'],
      ['2', 'snow_depth_24h'],
      ['2', 'snow_depth'],
      ['3', 'intermittent_snow'],
    ],
  },
  {
    slug: 'mt-washington',
    legacySlug: 'mtwashington',
    displayName: 'Mt. Washington',
    region: 'Snoqualmie Pass',
    stids: ['20'],
    columns: [
      ['20', 'air_temp'],
      ['20', 'wind_direction'],
      ['20', 'relative_humidity'],
      ['20', 'solar_radiation'],
    ],
  },
  {
    slug: 'snoqualmie-pass',
    legacySlug: 'snoqualmiepass',
    displayName: 'Snoqualmie Pass',
    region: 'Snoqualmie Pass',
    stids: ['22', '23', '21'],
    columns: [
      ['22', 'air_temp'],
      ['23', 'air_temp'],
      ['21', 'air_temp'],
      ['21', 'relative_humidity'],
      ['22', 'wind_speed_min'],
      ['22', 'wind_speed'],
      ['22', 'wind_gust'],
      ['22', 'wind_direction'],
      ['21', 'precip_accum_one_hour'],
      ['21', 'snow_depth_24h'],
      ['21', 'snow_depth'],
      ['21', 'pressure'],
    ],
  },
  {
    slug: 'crystal-mt-ski-area',
    legacySlug: 'crystalskiarea',
    displayName: 'Crystal Mt. Ski Area',
    region: 'Crystal Mt.',
    stids: ['29', '28'],
    columns: [
      ['29', 'air_temp'],
      ['28', 'air_temp'],
      ['29', 'relative_humidity'],
      ['28', 'relative_humidity'],
      ['29', 'wind_speed_min'],
      ['29', 'wind_speed'],
      ['29', 'wind_gust'],
      ['29', 'wind_direction'],
      ['28', 'precip_accum_one_hour'],
      ['28', 'snow_depth_24h'],
      ['28', 'snow_depth'],
    ],
  },
  {
    slug: 'crystal-mt-green-valley',
    legacySlug: 'crystalgrnvalley',
    displayName: 'Crystal Mt. - Green Valley & Campbell Basin',
    region: 'Crystal Mt.',
    stids: ['27', '54'],
    columns: [
      ['27', 'air_temp'],
      ['54', 'air_temp'],
      ['27', 'relative_humidity'],
      ['27', 'snow_depth_24h'],
      ['27', 'snow_depth'],
      ['54', 'snow_depth_24h'],
      ['54', 'snow_depth'],
    ],
  },
  {
    slug: 'camp-muir',
    legacySlug: 'campmuir',
    displayName: 'Camp Muir',
    region: 'Mt Rainier',
    stids: ['34'],
    columns: [
      ['34', 'air_temp'],
      ['34', 'relative_humidity'],
      ['34', 'wind_speed_min'],
      ['34', 'wind_speed'],
      ['34', 'wind_gust'],
      ['34', 'wind_direction'],
      ['34', 'solar_radiation'],
    ],
  },
  {
    slug: 'paradise',
    legacySlug: 'paradise',
    displayName: 'Paradise',
    region: 'Mt Rainier',
    stids: ['35', '36'],
    columns: [
      ['35', 'air_temp'],
      ['35', 'relative_humidity'],
      ['36', 'wind_speed_min'],
      ['36', 'wind_speed'],
      ['36', 'wind_gust'],
      ['36', 'wind_direction'],
      ['35', 'precip_accum_one_hour'],
      ['35', 'snow_depth_24h'],
      ['35', 'snow_depth'],
      ['36', 'solar_radiation'],
    ],
  },
  {
    slug: 'sunrise',
    legacySlug: 'sunrise',
    displayName: 'Sunrise',
    region: 'Mt Rainier',
    stids: ['30', '31'],
    columns: [
      ['30', 'air_temp'],
      ['31', 'air_temp'],
      ['30', 'relative_humidity'],
      ['31', 'relative_humidity'],
      ['30', 'wind_speed_min'],
      ['30', 'wind_speed'],
      ['30', 'wind_gust'],
      ['30', 'wind_direction'],
      ['31', 'snow_depth'],
    ],
  },
  {
    slug: 'chinook-pass',
    legacySlug: 'chinookpass',
    displayName: 'Chinook Pass',
    region: 'Chinook Pass',
    stids: ['32', '33'],
    columns: [
      ['32', 'air_temp'],
      ['33', 'air_temp'],
      ['32', 'relative_humidity'],
      ['33', 'relative_humidity'],
      ['32', 'wind_speed'],
      ['32', 'wind_gust'],
      ['32', 'wind_direction'],
      ['33', 'precip_accum_one_hour'],
      ['33', 'snow_depth'],
      ['33', 'equip_temperature'],
    ],
  },
  {
    slug: 'white-pass',
    legacySlug: 'whitepass',
    displayName: 'White Pass',
    region: 'White Pass',
    stids: ['39', '37', '49'],
    columns: [
      ['39', 'air_temp'],
      ['37', 'air_temp'],
      ['39', 'relative_humidity'],
      ['37', 'relative_humidity'],
      ['49', 'wind_speed_min'],
      ['49', 'wind_speed'],
      ['49', 'wind_gust'],
      ['49', 'wind_direction'],
      ['39', 'precip_accum_one_hour'],
      ['39', 'snow_depth_24h'],
      ['39', 'snow_depth'],
    ],
  },
  {
    slug: 'mt-st-helens',
    legacySlug: 'mtsthelens',
    displayName: 'Mt. St. Helens',
    region: 'Mt St Helens',
    stids: ['40'],
    columns: [
      ['40', 'air_temp'],
      ['40', 'relative_humidity'],
      ['40', 'wind_speed_min'],
      ['40', 'wind_speed'],
      ['40', 'wind_gust'],
      ['40', 'wind_direction'],
      ['40', 'precip_accum_one_hour'],
    ],
  },
  {
    slug: 'mazama',
    legacySlug: 'mazama',
    displayName: 'Mazama',
    region: 'Washington Pass',
    stids: ['7'],
    columns: [
      ['7', 'air_temp'],
      ['7', 'relative_humidity'],
      ['7', 'wind_speed'],
      ['7', 'wind_gust'],
      ['7', 'wind_direction'],
      ['7', 'precip_accum_one_hour'],
      ['7', 'snow_depth_24h'],
      ['7', 'snow_depth'],
      ['7', 'solar_radiation'],
    ],
  },
  {
    slug: 'washington-pass',
    legacySlug: 'washingtonpass',
    displayName: 'Washington Pass',
    region: 'Washington Pass',
    stids: ['9', '8'],
    columns: [
      ['9', 'air_temp'],
      ['8', 'air_temp'],
      ['9', 'relative_humidity'],
      ['8', 'relative_humidity'],
      ['9', 'wind_speed_min'],
      ['9', 'wind_speed'],
      ['9', 'wind_gust'],
      ['9', 'wind_direction'],
      ['8', 'precip_accum_one_hour'],
      ['8', 'snow_depth'],
      ['8', 'equip_temperature'],
    ],
  },
  {
    slug: 'blewett-pass',
    legacySlug: 'blewettpass',
    displayName: 'Blewett Pass',
    region: 'Lake Wenatchee to Mission Ridge',
    stids: ['48'],
    columns: [
      ['48', 'air_temp'],
      ['48', 'relative_humidity'],
      ['48', 'precip_accum_one_hour'],
      ['48', 'snow_depth_24h'],
      ['48', 'snow_depth'],
      ['48', 'pressure'],
      ['48', 'equip_temperature'],
    ],
  },
  {
    slug: 'dirtyface-summit',
    legacySlug: 'dirtyfacemtn',
    displayName: 'Dirtyface Summit',
    region: 'Lake Wenatchee to Mission Ridge',
    stids: ['10'],
    columns: [
      ['10', 'air_temp'],
      ['10', 'relative_humidity'],
      ['10', 'wind_speed_min'],
      ['10', 'wind_speed'],
      ['10', 'wind_gust'],
      ['10', 'wind_direction'],
    ],
  },
  {
    slug: 'lake-wenatchee',
    legacySlug: 'lakewenatchee',
    displayName: 'Lake Wenatchee',
    region: 'Lake Wenatchee to Mission Ridge',
    stids: ['11'],
    columns: [
      ['11', 'air_temp'],
      ['11', 'relative_humidity'],
      ['11', 'precip_accum_one_hour'],
      ['11', 'snow_depth_24h'],
      ['11', 'snow_depth'],
    ],
  },
  {
    slug: 'mission-ridge-ski-area',
    legacySlug: 'missionridge',
    displayName: 'Mission Ridge Ski Area',
    region: 'Lake Wenatchee to Mission Ridge',
    stids: ['25', '26', '24'],
    columns: [
      ['25', 'air_temp'],
      ['26', 'air_temp'],
      ['24', 'air_temp'],
      ['25', 'relative_humidity'],
      ['26', 'relative_humidity'],
      ['25', 'wind_speed_min'],
      ['25', 'wind_speed'],
      ['25', 'wind_gust'],
      ['25', 'wind_direction'],
      ['26', 'precip_accum_one_hour'],
      ['26', 'snow_depth_24h'],
      ['26', 'snow_depth'],
    ],
  },
  {
    slug: 'tumwater-leavenworth',
    legacySlug: 'tumwater',
    displayName: 'Tumwater Mt. & Leavenworth',
    region: 'Lake Wenatchee to Mission Ridge',
    stids: ['19', '53'],
    columns: [
      ['19', 'air_temp'],
      ['53', 'air_temp'],
      ['19', 'relative_humidity'],
      ['53', 'relative_humidity'],
      ['19', 'wind_speed_min'],
      ['19', 'wind_speed'],
      ['19', 'wind_gust'],
      ['19', 'wind_direction'],
      ['53', 'precip_accum_one_hour'],
      ['53', 'snow_depth_24h'],
      ['53', 'snow_depth'],
      ['19', 'snow_depth'],
    ],
  },
  {
    slug: 'mt-hood-meadows-ski-area',
    legacySlug: 'mthoodmeadows',
    displayName: 'Mt. Hood Meadows Ski Area',
    region: 'Mt Hood',
    stids: ['42', '43'],
    columns: [
      ['42', 'air_temp'],
      ['43', 'air_temp'],
      ['42', 'relative_humidity'],
      ['43', 'relative_humidity'],
      ['42', 'wind_speed_min'],
      ['42', 'wind_speed'],
      ['42', 'wind_gust'],
      ['42', 'wind_direction'],
      ['43', 'precip_accum_one_hour'],
      ['43', 'snow_depth_24h'],
      ['43', 'snow_depth'],
      ['43', 'pressure'],
    ],
  },
  {
    slug: 'mt-hood-meadows-cascade-express',
    legacySlug: 'cascade_express',
    displayName: 'Mt. Hood Meadows - Cascade Express',
    region: 'Mt Hood',
    stids: ['41'],
    columns: [
      ['41', 'air_temp'],
      ['41', 'relative_humidity'],
      ['41', 'wind_speed_min'],
      ['41', 'wind_speed'],
      ['41', 'wind_gust'],
      ['41', 'wind_direction'],
    ],
  },
  {
    slug: 'timberline-lodge',
    legacySlug: 'timberlinebase',
    displayName: 'Timberline Lodge',
    region: 'Mt Hood',
    stids: ['44', '56'],
    columns: [
      ['44', 'air_temp'],
      ['44', 'relative_humidity'],
      ['56', 'wind_speed_min'],
      ['56', 'wind_speed'],
      ['56', 'wind_gust'],
      ['56', 'wind_direction'],
      ['44', 'precip_accum_one_hour'],
      ['44', 'snow_depth_24h'],
      ['44', 'snow_depth'],
    ],
  },
  {
    slug: 'timberline-magic-mile',
    legacySlug: 'timberlineupper',
    displayName: 'Timberline - Magic Mile',
    region: 'Mt Hood',
    stids: ['45'],
    columns: [
      ['45', 'air_temp'],
      ['45', 'relative_humidity'],
      ['45', 'wind_speed_min'],
      ['45', 'wind_speed'],
      ['45', 'wind_gust'],
      ['45', 'wind_direction'],
    ],
  },
  {
    slug: 'skibowl-ski-area',
    legacySlug: 'skibowlgovtcamp',
    displayName: 'Skibowl Ski Area',
    region: 'Mt Hood',
    stids: ['47', '46'],
    columns: [
      ['47', 'air_temp'],
      ['46', 'air_temp'],
      ['47', 'relative_humidity'],
      ['46', 'relative_humidity'],
      ['47', 'wind_speed_min'],
      ['47', 'wind_speed'],
      ['47', 'wind_gust'],
      ['47', 'wind_direction'],
      ['46', 'precip_accum_one_hour'],
      ['47', 'snow_depth'],
    ],
  },
]

const STATION_GROUPS_BY_SLUG = new Map(WEATHER_STATION_GROUPS.map((g) => [g.slug, g]))

export function getStationGroup(slug: string): WeatherStationGroup | undefined {
  return STATION_GROUPS_BY_SLUG.get(slug)
}
